# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: self-hosted

    strategy:
      matrix:
        node-version: [14.x]

    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - run: npm install -save --legacy-peer-deps
    
  deploy:
  
    needs: build
    runs-on: self-hosted
    
    steps:
    - name: copy and run
      env: 
        DEPLOY_PATH: ${{ secrets.DEPLOY_PATH }}
        RUNNER_WORK_PATH: ${{ secrets.RUNNER_WORK_PATH }}
      run: |
        sudo rm -rf $DEPLOY_PATH/Goraku-client
        sudo mv $RUNNER_WORK_PATH/Goraku-client/Goraku-client $DEPLOY_PATH
        sudo npm run build $DEPLOY_PATH/Goraku-client
        sudo sh $DEPLOY_PATH/run.sh
